In [3]:
from PIL import Image
import numpy as np
from sklearn.preprocessing import StandardScaler



In [4]:

img = Image.open('images.jpeg').convert('L') 
img_array = np.array(img)  
img_flattened = img_array.reshape(-1, img_array.shape[1])  
scaler = StandardScaler()
img_scaled = scaler.fit_transform(img_flattened)  
print(img_scaled)



[[-0.41176631 -0.38988148 -0.38325767 ... -0.2773534  -0.2770243
  -0.27681147]
 [-0.41176631 -0.38988148 -0.38325767 ... -0.2773534  -0.2770243
  -0.27681147]
 [-0.41176631 -0.38988148 -0.38325767 ... -0.2773534  -0.2770243
  -0.27681147]
 ...
 [-0.53598859 -0.56209241 -0.58889785 ... -0.7393105  -0.73856874
  -0.7377306 ]
 [-0.56083304 -0.56209241 -0.56319283 ... -0.7393105  -0.73856874
  -0.7377306 ]
 [-0.64778864 -0.64157438 -0.60175037 ... -0.7393105  -0.73856874
  -0.7377306 ]]


In [5]:

cov_matrix_img = np.cov(img_scaled.T)
print(cov_matrix_img)



[[1.00549451 0.99108302 0.97872341 ... 0.9017542  0.90169576 0.90189456]
 [0.99108302 1.00549451 0.99921041 ... 0.9405697  0.94053299 0.94062244]
 [0.97872341 0.99921041 1.00549451 ... 0.93945672 0.93985906 0.94056423]
 ...
 [0.9017542  0.9405697  0.93945672 ... 1.00549451 1.00546992 1.0053394 ]
 [0.90169576 0.94053299 0.93985906 ... 1.00546992 1.00549451 1.00543341]
 [0.90189456 0.94062244 0.94056423 ... 1.0053394  1.00543341 1.00549451]]


In [6]:

eigenvalues_img, eigenvectors_img = np.linalg.eig(cov_matrix_img)
print(eigenvalues_img)
print(eigenvectors_img)


[ 1.36919238e+02+0.00000000e+00j  4.89750440e+01+0.00000000e+00j
  2.10568074e+01+0.00000000e+00j  1.58981452e+01+0.00000000e+00j
  1.00938526e+01+0.00000000e+00j  6.18071270e+00+0.00000000e+00j
  5.44043848e+00+0.00000000e+00j  3.44306993e+00+0.00000000e+00j
  2.97347892e+00+0.00000000e+00j  2.48595824e+00+0.00000000e+00j
  2.14842910e+00+0.00000000e+00j  1.83274158e+00+0.00000000e+00j
  1.48485559e+00+0.00000000e+00j  1.32178035e+00+0.00000000e+00j
  1.23523123e+00+0.00000000e+00j  1.05561013e+00+0.00000000e+00j
  9.18065732e-01+0.00000000e+00j  8.66580659e-01+0.00000000e+00j
  7.55333473e-01+0.00000000e+00j  7.36593573e-01+0.00000000e+00j
  6.72570422e-01+0.00000000e+00j  6.06070193e-01+0.00000000e+00j
  5.37662502e-01+0.00000000e+00j  5.15444555e-01+0.00000000e+00j
  4.71567877e-01+0.00000000e+00j  4.64157139e-01+0.00000000e+00j
  4.12623986e-01+0.00000000e+00j  3.69603260e-01+0.00000000e+00j
  3.18102633e-01+0.00000000e+00j  3.02758442e-01+0.00000000e+00j
  2.90608312e-01+0.000000

In [7]:

sorted_idx_img = np.argsort(eigenvalues_img)[::-1]  
eigenvalues_sorted_img = eigenvalues_img[sorted_idx_img]
eigenvectors_sorted_img = eigenvectors_img[:, sorted_idx_img]
print(eigenvalues_sorted_img)
print(eigenvectors_sorted_img)


[ 1.36919238e+02+0.00000000e+00j  4.89750440e+01+0.00000000e+00j
  2.10568074e+01+0.00000000e+00j  1.58981452e+01+0.00000000e+00j
  1.00938526e+01+0.00000000e+00j  6.18071270e+00+0.00000000e+00j
  5.44043848e+00+0.00000000e+00j  3.44306993e+00+0.00000000e+00j
  2.97347892e+00+0.00000000e+00j  2.48595824e+00+0.00000000e+00j
  2.14842910e+00+0.00000000e+00j  1.83274158e+00+0.00000000e+00j
  1.48485559e+00+0.00000000e+00j  1.32178035e+00+0.00000000e+00j
  1.23523123e+00+0.00000000e+00j  1.05561013e+00+0.00000000e+00j
  9.18065732e-01+0.00000000e+00j  8.66580659e-01+0.00000000e+00j
  7.55333473e-01+0.00000000e+00j  7.36593573e-01+0.00000000e+00j
  6.72570422e-01+0.00000000e+00j  6.06070193e-01+0.00000000e+00j
  5.37662502e-01+0.00000000e+00j  5.15444555e-01+0.00000000e+00j
  4.71567877e-01+0.00000000e+00j  4.64157139e-01+0.00000000e+00j
  4.12623986e-01+0.00000000e+00j  3.69603260e-01+0.00000000e+00j
  3.18102633e-01+0.00000000e+00j  3.02758442e-01+0.00000000e+00j
  2.90608312e-01+0.000000

In [8]:

k_img = 50
eigenvectors_k_img = eigenvectors_sorted_img[:, :k_img]
print(eigenvectors_k_img)


[[-0.07750579+0.j  0.03646203+0.j  0.02067089+0.j ...  0.01991694+0.j
   0.01487071+0.j -0.01422512+0.j]
 [-0.08045823+0.j  0.0314682 +0.j  0.01677347+0.j ... -0.03275542+0.j
   0.00058406+0.j  0.01050281+0.j]
 [-0.08069026+0.j  0.02918245+0.j  0.01687496+0.j ... -0.0586341 +0.j
  -0.04226228+0.j  0.00176902+0.j]
 ...
 [-0.08318732+0.j  0.01892425+0.j -0.0075888 +0.j ... -0.02818085+0.j
  -0.02155527+0.j  0.00257072+0.j]
 [-0.08321133+0.j  0.01878685+0.j -0.00761871+0.j ... -0.02718482+0.j
  -0.02192209+0.j  0.00250491+0.j]
 [-0.08324183+0.j  0.01862242+0.j -0.0076338 +0.j ... -0.0257697 +0.j
  -0.02378741+0.j  0.00341518+0.j]]


In [9]:
img_transformed = np.dot(img_scaled, eigenvectors_k_img)

print("Transformed Image Data with 50 components:")
print(img_transformed)


Transformed Image Data with 50 components:
[[ 5.11645801e+00+0.j  7.95972431e+00+0.j  1.42618112e-01+0.j ...
   1.89445581e-02+0.j -1.87902019e-03+0.j  6.75352426e-02+0.j]
 [ 5.11645801e+00+0.j  7.95972431e+00+0.j  1.42618112e-01+0.j ...
   1.89445581e-02+0.j -1.87902019e-03+0.j  6.75352426e-02+0.j]
 [ 5.11645801e+00+0.j  7.95972431e+00+0.j  1.42618112e-01+0.j ...
   1.89445581e-02+0.j -1.87902019e-03+0.j  6.75352426e-02+0.j]
 ...
 [ 1.30494391e+01+0.j  1.39371507e+01+0.j  2.86870049e+00+0.j ...
  -1.35229781e-01+0.j -4.82363342e-02+0.j -7.60698590e-02+0.j]
 [ 1.31355645e+01+0.j  1.39791968e+01+0.j  2.88588537e+00+0.j ...
  -1.49780856e-01+0.j -4.26972948e-02+0.j -8.60689003e-02+0.j]
 [ 1.32430289e+01+0.j  1.40830181e+01+0.j  2.90415313e+00+0.j ...
  -1.64537035e-01+0.j -5.07517565e-02+0.j -9.10860476e-02+0.j]]
