In [15]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import numpy as np

In [16]:
# Load the Iris dataset
iris = load_iris()
X_iris = iris.data
y_iris = iris.target

In [17]:
# Initialize the Gaussian Naïve Bayes classifier
nb_gaussian = GaussianNB()

In [18]:
# Split data into train and test sets for final evaluation
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

In [19]:
# Fit the model on the training set
nb_gaussian.fit(X_train_iris, y_train_iris)

# Make predictions on the test set
y_pred_iris = nb_gaussian.predict(X_test_iris)


In [20]:
# Evaluation metrics
conf_matrix = confusion_matrix(y_test_iris, y_pred_iris)
accuracy = accuracy_score(y_test_iris, y_pred_iris)
classification_rep = classification_report(y_test_iris, y_pred_iris)

In [21]:
# Print results
print("Cross-Validation Accuracy Scores:", cross_val_scores)
print("Average Cross-Validation Accuracy:", np.mean(cross_val_scores))
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("\nClassification Report:")
print(classification_rep)

Cross-Validation Accuracy Scores: [0.93333333 0.96666667 0.93333333 0.93333333 1.        ]
Average Cross-Validation Accuracy: 0.9533333333333334

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

